In [2]:
import os
import numpy as np
import pandas as pd

In [116]:
# 設定 data_path, 並讀取 app_train
dir_data = 'C:\\Users\\Zhong\\Documents\\GitHub\\2nd-ML100Days\\data\\home-credit-default-risk'
f_app_train = os.path.join(dir_data, 'application_train.csv')
app_train = pd.read_csv(f_app_train)

## 作業
將下列部分資料片段 sub_train 使用 One Hot encoding, 並觀察轉換前後的欄位數量 (使用 shape) 與欄位名稱 (使用 head) 變化

In [117]:
sub_train = pd.DataFrame(app_train['WEEKDAY_APPR_PROCESS_START'])
print(sub_train.shape)
sub_train.head(5)

(307511, 1)


WEEKDAY_APPR_PROCESS_START
0                  WEDNESDAY
1                     MONDAY
2                     MONDAY
3                  WEDNESDAY
4                   THURSDAY

In [118]:
"""
Your Code Here
"""
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
le = LabelEncoder()
le.fit(sub_train['WEEKDAY_APPR_PROCESS_START'])
sub_train['WEEKDAY_APPR_PROCESS_START']=le.transform(sub_train['WEEKDAY_APPR_PROCESS_START'])


In [122]:
onehotencoder = OneHotEncoder(categorical_features = [0])
k=onehotencoder.fit_transform(sub_train.values).toarray()
print(k[1:5])
print(type(sub_train.values))
#print(sub_train.shape)
#sub_train.head(5)

[[0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]]
<class 'numpy.ndarray'>


In [123]:
sub_train.apply(pd.Series.nunique, axis = 0)


WEEKDAY_APPR_PROCESS_START    7
dtype: int64